#ifndef USERINTERFACELIB_H
#define USERINTERFACELIB_H

#include <QtGlobal>

#ifdef USERINTERFACE_EXPORT
# define USERINTERFACE_API Q_DECL_EXPORT
#else
# define USERINTERFACE_API Q_DECL_IMPORT
#endif

#endif // USERINTERFACELIB_H
